#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH


#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..."

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url


#=================================================
# CONFIGURE TOOLPIC BACKEND
#=================================================

git clone https://github.com/youthforclimatefr/ToolpicBackend $final_path

ynh_replace_string "YNH_LOCATION" "$final_path" ../conf/toolpic-api.service
ynh_replace_string "YNH_USER" "$app" ../conf/toolpic-api.service

cp ../conf/toolpic-api.service /etc/systemd/system/$app.service


# Create a system user
ynh_system_user_create --username=$app

# Set write access
chown -R $app: "$final_path"

cd "$final_path" && exec_as "$app" npm i

#=================================================
# CONFIGURE NGINX
#=================================================

# Nginx configuration
ynh_replace_string "YNH_LOCATION" "$path_url" ../conf/nginx-proxy.conf

cp ../conf/nginx-proxy.conf /etc/nginx/conf.d/$domain.d/$app.conf


#=================================================
# CONFIGURE SSOWAT
#=================================================

# Make app public if necessary
ynh_app_setting_set "$app" unprotected_uris "/"

service $app start

# Reload Nginx and regenerate SSOwat conf
systemctl reload nginx
